//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace fiscalCalendar.prmExternalsSvc {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfResourceStruct", Namespace="http://tempuri.org/", ItemName="resourceStruct")]
    public class ArrayOfResourceStruct : System.Collections.ObjectModel.ObservableCollection<fiscalCalendar.prmExternalsSvc.resourceStruct> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="resourceStruct", Namespace="http://tempuri.org/")]
    public partial class resourceStruct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string employeeIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string departmentField;
        
        private int shiftField;
        
        private bool activeField;
        
        private string ee_groupField;
        
        private int sch_hoursField;
        
        private string titleField;
        
        private System.DateTime hireDateField;
        
        private string emailField;
        
        private string userNameField;
        
        private string supervisorIdField;
        
        private string phoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string employeeId {
            get {
                return this.employeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.employeeIdField, value) != true)) {
                    this.employeeIdField = value;
                    this.RaisePropertyChanged("employeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int shift {
            get {
                return this.shiftField;
            }
            set {
                if ((this.shiftField.Equals(value) != true)) {
                    this.shiftField = value;
                    this.RaisePropertyChanged("shift");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ee_group {
            get {
                return this.ee_groupField;
            }
            set {
                if ((object.ReferenceEquals(this.ee_groupField, value) != true)) {
                    this.ee_groupField = value;
                    this.RaisePropertyChanged("ee_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int sch_hours {
            get {
                return this.sch_hoursField;
            }
            set {
                if ((this.sch_hoursField.Equals(value) != true)) {
                    this.sch_hoursField = value;
                    this.RaisePropertyChanged("sch_hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime hireDate {
            get {
                return this.hireDateField;
            }
            set {
                if ((this.hireDateField.Equals(value) != true)) {
                    this.hireDateField = value;
                    this.RaisePropertyChanged("hireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string supervisorId {
            get {
                return this.supervisorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.supervisorIdField, value) != true)) {
                    this.supervisorIdField = value;
                    this.RaisePropertyChanged("supervisorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfJobStruct", Namespace="http://tempuri.org/", ItemName="jobStruct")]
    public class ArrayOfJobStruct : System.Collections.ObjectModel.ObservableCollection<fiscalCalendar.prmExternalsSvc.jobStruct> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jobStruct", Namespace="http://tempuri.org/")]
    public partial class jobStruct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jobNoField;
        
        private string jobDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string jobNo {
            get {
                return this.jobNoField;
            }
            set {
                if ((object.ReferenceEquals(this.jobNoField, value) != true)) {
                    this.jobNoField = value;
                    this.RaisePropertyChanged("jobNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jobDesc {
            get {
                return this.jobDescField;
            }
            set {
                if ((object.ReferenceEquals(this.jobDescField, value) != true)) {
                    this.jobDescField = value;
                    this.RaisePropertyChanged("jobDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="invoiceType", Namespace="http://tempuri.org/")]
    public enum invoiceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        estimate = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        quote = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        invoice = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPeriodStructure", Namespace="http://tempuri.org/", ItemName="periodStructure")]
    public class ArrayOfPeriodStructure : System.Collections.ObjectModel.ObservableCollection<fiscalCalendar.prmExternalsSvc.periodStructure> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="periodStructure", Namespace="http://tempuri.org/")]
    public partial class periodStructure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime calDateField;
        
        private int fiscalWeekField;
        
        private int fiscalPeriodField;
        
        private int fiscalQuarterField;
        
        private int fiscalYearField;
        
        private bool workDayField;
        
        private string displayNumField;
        
        private string displayWeekField;
        
        private string displayBgndField;
        
        private string displayQtrField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime calDate {
            get {
                return this.calDateField;
            }
            set {
                if ((this.calDateField.Equals(value) != true)) {
                    this.calDateField = value;
                    this.RaisePropertyChanged("calDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int fiscalWeek {
            get {
                return this.fiscalWeekField;
            }
            set {
                if ((this.fiscalWeekField.Equals(value) != true)) {
                    this.fiscalWeekField = value;
                    this.RaisePropertyChanged("fiscalWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int fiscalPeriod {
            get {
                return this.fiscalPeriodField;
            }
            set {
                if ((this.fiscalPeriodField.Equals(value) != true)) {
                    this.fiscalPeriodField = value;
                    this.RaisePropertyChanged("fiscalPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int fiscalQuarter {
            get {
                return this.fiscalQuarterField;
            }
            set {
                if ((this.fiscalQuarterField.Equals(value) != true)) {
                    this.fiscalQuarterField = value;
                    this.RaisePropertyChanged("fiscalQuarter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int fiscalYear {
            get {
                return this.fiscalYearField;
            }
            set {
                if ((this.fiscalYearField.Equals(value) != true)) {
                    this.fiscalYearField = value;
                    this.RaisePropertyChanged("fiscalYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool workDay {
            get {
                return this.workDayField;
            }
            set {
                if ((this.workDayField.Equals(value) != true)) {
                    this.workDayField = value;
                    this.RaisePropertyChanged("workDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string displayNum {
            get {
                return this.displayNumField;
            }
            set {
                if ((object.ReferenceEquals(this.displayNumField, value) != true)) {
                    this.displayNumField = value;
                    this.RaisePropertyChanged("displayNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string displayWeek {
            get {
                return this.displayWeekField;
            }
            set {
                if ((object.ReferenceEquals(this.displayWeekField, value) != true)) {
                    this.displayWeekField = value;
                    this.RaisePropertyChanged("displayWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string displayBgnd {
            get {
                return this.displayBgndField;
            }
            set {
                if ((object.ReferenceEquals(this.displayBgndField, value) != true)) {
                    this.displayBgndField = value;
                    this.RaisePropertyChanged("displayBgnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string displayQtr {
            get {
                return this.displayQtrField;
            }
            set {
                if ((object.ReferenceEquals(this.displayQtrField, value) != true)) {
                    this.displayQtrField = value;
                    this.RaisePropertyChanged("displayQtr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="prmExternalsSvc.prmExternalsSoap")]
    public interface prmExternalsSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(fiscalCalendar.prmExternalsSvc.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        fiscalCalendar.prmExternalsSvc.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/sendResources", ReplyAction="*")]
        System.IAsyncResult BeginsendResources(fiscalCalendar.prmExternalsSvc.sendResourcesRequest request, System.AsyncCallback callback, object asyncState);
        
        fiscalCalendar.prmExternalsSvc.sendResourcesResponse EndsendResources(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/listJobs", ReplyAction="*")]
        System.IAsyncResult BeginlistJobs(fiscalCalendar.prmExternalsSvc.listJobsRequest request, System.AsyncCallback callback, object asyncState);
        
        fiscalCalendar.prmExternalsSvc.listJobsResponse EndlistJobs(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/sendInvoices", ReplyAction="*")]
        System.IAsyncResult BeginsendInvoices(fiscalCalendar.prmExternalsSvc.sendInvoicesRequest request, System.AsyncCallback callback, object asyncState);
        
        fiscalCalendar.prmExternalsSvc.sendInvoicesResponse EndsendInvoices(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/fiscalPeriods", ReplyAction="*")]
        System.IAsyncResult BeginfiscalPeriods(fiscalCalendar.prmExternalsSvc.fiscalPeriodsRequest request, System.AsyncCallback callback, object asyncState);
        
        fiscalCalendar.prmExternalsSvc.fiscalPeriodsResponse EndfiscalPeriods(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(fiscalCalendar.prmExternalsSvc.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(fiscalCalendar.prmExternalsSvc.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendResourcesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendResources", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.sendResourcesRequestBody Body;
        
        public sendResourcesRequest() {
        }
        
        public sendResourcesRequest(fiscalCalendar.prmExternalsSvc.sendResourcesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendResourcesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public fiscalCalendar.prmExternalsSvc.ArrayOfResourceStruct employees;
        
        public sendResourcesRequestBody() {
        }
        
        public sendResourcesRequestBody(fiscalCalendar.prmExternalsSvc.ArrayOfResourceStruct employees) {
            this.employees = employees;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendResourcesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendResourcesResponse", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.sendResourcesResponseBody Body;
        
        public sendResourcesResponse() {
        }
        
        public sendResourcesResponse(fiscalCalendar.prmExternalsSvc.sendResourcesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendResourcesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendResourcesResult;
        
        public sendResourcesResponseBody() {
        }
        
        public sendResourcesResponseBody(bool sendResourcesResult) {
            this.sendResourcesResult = sendResourcesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listJobsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listJobs", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.listJobsRequestBody Body;
        
        public listJobsRequest() {
        }
        
        public listJobsRequest(fiscalCalendar.prmExternalsSvc.listJobsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listJobsRequestBody {
        
        public listJobsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listJobsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listJobsResponse", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.listJobsResponseBody Body;
        
        public listJobsResponse() {
        }
        
        public listJobsResponse(fiscalCalendar.prmExternalsSvc.listJobsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listJobsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public fiscalCalendar.prmExternalsSvc.ArrayOfJobStruct listJobsResult;
        
        public listJobsResponseBody() {
        }
        
        public listJobsResponseBody(fiscalCalendar.prmExternalsSvc.ArrayOfJobStruct listJobsResult) {
            this.listJobsResult = listJobsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendInvoicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendInvoices", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.sendInvoicesRequestBody Body;
        
        public sendInvoicesRequest() {
        }
        
        public sendInvoicesRequest(fiscalCalendar.prmExternalsSvc.sendInvoicesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendInvoicesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public fiscalCalendar.prmExternalsSvc.invoiceType iType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jobno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal amt;
        
        public sendInvoicesRequestBody() {
        }
        
        public sendInvoicesRequestBody(fiscalCalendar.prmExternalsSvc.invoiceType iType, string jobno, decimal amt) {
            this.iType = iType;
            this.jobno = jobno;
            this.amt = amt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendInvoicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendInvoicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.sendInvoicesResponseBody Body;
        
        public sendInvoicesResponse() {
        }
        
        public sendInvoicesResponse(fiscalCalendar.prmExternalsSvc.sendInvoicesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendInvoicesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendInvoicesResult;
        
        public sendInvoicesResponseBody() {
        }
        
        public sendInvoicesResponseBody(bool sendInvoicesResult) {
            this.sendInvoicesResult = sendInvoicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fiscalPeriodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fiscalPeriods", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.fiscalPeriodsRequestBody Body;
        
        public fiscalPeriodsRequest() {
        }
        
        public fiscalPeriodsRequest(fiscalCalendar.prmExternalsSvc.fiscalPeriodsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class fiscalPeriodsRequestBody {
        
        public fiscalPeriodsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fiscalPeriodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fiscalPeriodsResponse", Namespace="http://tempuri.org/", Order=0)]
        public fiscalCalendar.prmExternalsSvc.fiscalPeriodsResponseBody Body;
        
        public fiscalPeriodsResponse() {
        }
        
        public fiscalPeriodsResponse(fiscalCalendar.prmExternalsSvc.fiscalPeriodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fiscalPeriodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public fiscalCalendar.prmExternalsSvc.ArrayOfPeriodStructure fiscalPeriodsResult;
        
        public fiscalPeriodsResponseBody() {
        }
        
        public fiscalPeriodsResponseBody(fiscalCalendar.prmExternalsSvc.ArrayOfPeriodStructure fiscalPeriodsResult) {
            this.fiscalPeriodsResult = fiscalPeriodsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface prmExternalsSoapChannel : fiscalCalendar.prmExternalsSvc.prmExternalsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sendResourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public sendResourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class listJobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public listJobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public fiscalCalendar.prmExternalsSvc.ArrayOfJobStruct Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((fiscalCalendar.prmExternalsSvc.ArrayOfJobStruct)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sendInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public sendInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class fiscalPeriodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public fiscalPeriodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public fiscalCalendar.prmExternalsSvc.ArrayOfPeriodStructure Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((fiscalCalendar.prmExternalsSvc.ArrayOfPeriodStructure)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class prmExternalsSoapClient : System.ServiceModel.ClientBase<fiscalCalendar.prmExternalsSvc.prmExternalsSoap>, fiscalCalendar.prmExternalsSvc.prmExternalsSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginsendResourcesDelegate;
        
        private EndOperationDelegate onEndsendResourcesDelegate;
        
        private System.Threading.SendOrPostCallback onsendResourcesCompletedDelegate;
        
        private BeginOperationDelegate onBeginlistJobsDelegate;
        
        private EndOperationDelegate onEndlistJobsDelegate;
        
        private System.Threading.SendOrPostCallback onlistJobsCompletedDelegate;
        
        private BeginOperationDelegate onBeginsendInvoicesDelegate;
        
        private EndOperationDelegate onEndsendInvoicesDelegate;
        
        private System.Threading.SendOrPostCallback onsendInvoicesCompletedDelegate;
        
        private BeginOperationDelegate onBeginfiscalPeriodsDelegate;
        
        private EndOperationDelegate onEndfiscalPeriodsDelegate;
        
        private System.Threading.SendOrPostCallback onfiscalPeriodsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public prmExternalsSoapClient() {
        }
        
        public prmExternalsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public prmExternalsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public prmExternalsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public prmExternalsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<sendResourcesCompletedEventArgs> sendResourcesCompleted;
        
        public event System.EventHandler<listJobsCompletedEventArgs> listJobsCompleted;
        
        public event System.EventHandler<sendInvoicesCompletedEventArgs> sendInvoicesCompleted;
        
        public event System.EventHandler<fiscalPeriodsCompletedEventArgs> fiscalPeriodsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult fiscalCalendar.prmExternalsSvc.prmExternalsSoap.BeginHelloWorld(fiscalCalendar.prmExternalsSvc.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            fiscalCalendar.prmExternalsSvc.HelloWorldRequest inValue = new fiscalCalendar.prmExternalsSvc.HelloWorldRequest();
            inValue.Body = new fiscalCalendar.prmExternalsSvc.HelloWorldRequestBody();
            return ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fiscalCalendar.prmExternalsSvc.HelloWorldResponse fiscalCalendar.prmExternalsSvc.prmExternalsSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndHelloWorld(System.IAsyncResult result) {
            fiscalCalendar.prmExternalsSvc.HelloWorldResponse retVal = ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult fiscalCalendar.prmExternalsSvc.prmExternalsSoap.BeginsendResources(fiscalCalendar.prmExternalsSvc.sendResourcesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsendResources(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginsendResources(fiscalCalendar.prmExternalsSvc.ArrayOfResourceStruct employees, System.AsyncCallback callback, object asyncState) {
            fiscalCalendar.prmExternalsSvc.sendResourcesRequest inValue = new fiscalCalendar.prmExternalsSvc.sendResourcesRequest();
            inValue.Body = new fiscalCalendar.prmExternalsSvc.sendResourcesRequestBody();
            inValue.Body.employees = employees;
            return ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).BeginsendResources(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fiscalCalendar.prmExternalsSvc.sendResourcesResponse fiscalCalendar.prmExternalsSvc.prmExternalsSoap.EndsendResources(System.IAsyncResult result) {
            return base.Channel.EndsendResources(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndsendResources(System.IAsyncResult result) {
            fiscalCalendar.prmExternalsSvc.sendResourcesResponse retVal = ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).EndsendResources(result);
            return retVal.Body.sendResourcesResult;
        }
        
        private System.IAsyncResult OnBeginsendResources(object[] inValues, System.AsyncCallback callback, object asyncState) {
            fiscalCalendar.prmExternalsSvc.ArrayOfResourceStruct employees = ((fiscalCalendar.prmExternalsSvc.ArrayOfResourceStruct)(inValues[0]));
            return this.BeginsendResources(employees, callback, asyncState);
        }
        
        private object[] OnEndsendResources(System.IAsyncResult result) {
            bool retVal = this.EndsendResources(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsendResourcesCompleted(object state) {
            if ((this.sendResourcesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.sendResourcesCompleted(this, new sendResourcesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void sendResourcesAsync(fiscalCalendar.prmExternalsSvc.ArrayOfResourceStruct employees) {
            this.sendResourcesAsync(employees, null);
        }
        
        public void sendResourcesAsync(fiscalCalendar.prmExternalsSvc.ArrayOfResourceStruct employees, object userState) {
            if ((this.onBeginsendResourcesDelegate == null)) {
                this.onBeginsendResourcesDelegate = new BeginOperationDelegate(this.OnBeginsendResources);
            }
            if ((this.onEndsendResourcesDelegate == null)) {
                this.onEndsendResourcesDelegate = new EndOperationDelegate(this.OnEndsendResources);
            }
            if ((this.onsendResourcesCompletedDelegate == null)) {
                this.onsendResourcesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsendResourcesCompleted);
            }
            base.InvokeAsync(this.onBeginsendResourcesDelegate, new object[] {
                        employees}, this.onEndsendResourcesDelegate, this.onsendResourcesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult fiscalCalendar.prmExternalsSvc.prmExternalsSoap.BeginlistJobs(fiscalCalendar.prmExternalsSvc.listJobsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlistJobs(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginlistJobs(System.AsyncCallback callback, object asyncState) {
            fiscalCalendar.prmExternalsSvc.listJobsRequest inValue = new fiscalCalendar.prmExternalsSvc.listJobsRequest();
            inValue.Body = new fiscalCalendar.prmExternalsSvc.listJobsRequestBody();
            return ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).BeginlistJobs(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fiscalCalendar.prmExternalsSvc.listJobsResponse fiscalCalendar.prmExternalsSvc.prmExternalsSoap.EndlistJobs(System.IAsyncResult result) {
            return base.Channel.EndlistJobs(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private fiscalCalendar.prmExternalsSvc.ArrayOfJobStruct EndlistJobs(System.IAsyncResult result) {
            fiscalCalendar.prmExternalsSvc.listJobsResponse retVal = ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).EndlistJobs(result);
            return retVal.Body.listJobsResult;
        }
        
        private System.IAsyncResult OnBeginlistJobs(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginlistJobs(callback, asyncState);
        }
        
        private object[] OnEndlistJobs(System.IAsyncResult result) {
            fiscalCalendar.prmExternalsSvc.ArrayOfJobStruct retVal = this.EndlistJobs(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlistJobsCompleted(object state) {
            if ((this.listJobsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.listJobsCompleted(this, new listJobsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void listJobsAsync() {
            this.listJobsAsync(null);
        }
        
        public void listJobsAsync(object userState) {
            if ((this.onBeginlistJobsDelegate == null)) {
                this.onBeginlistJobsDelegate = new BeginOperationDelegate(this.OnBeginlistJobs);
            }
            if ((this.onEndlistJobsDelegate == null)) {
                this.onEndlistJobsDelegate = new EndOperationDelegate(this.OnEndlistJobs);
            }
            if ((this.onlistJobsCompletedDelegate == null)) {
                this.onlistJobsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlistJobsCompleted);
            }
            base.InvokeAsync(this.onBeginlistJobsDelegate, null, this.onEndlistJobsDelegate, this.onlistJobsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult fiscalCalendar.prmExternalsSvc.prmExternalsSoap.BeginsendInvoices(fiscalCalendar.prmExternalsSvc.sendInvoicesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsendInvoices(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginsendInvoices(fiscalCalendar.prmExternalsSvc.invoiceType iType, string jobno, decimal amt, System.AsyncCallback callback, object asyncState) {
            fiscalCalendar.prmExternalsSvc.sendInvoicesRequest inValue = new fiscalCalendar.prmExternalsSvc.sendInvoicesRequest();
            inValue.Body = new fiscalCalendar.prmExternalsSvc.sendInvoicesRequestBody();
            inValue.Body.iType = iType;
            inValue.Body.jobno = jobno;
            inValue.Body.amt = amt;
            return ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).BeginsendInvoices(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fiscalCalendar.prmExternalsSvc.sendInvoicesResponse fiscalCalendar.prmExternalsSvc.prmExternalsSoap.EndsendInvoices(System.IAsyncResult result) {
            return base.Channel.EndsendInvoices(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndsendInvoices(System.IAsyncResult result) {
            fiscalCalendar.prmExternalsSvc.sendInvoicesResponse retVal = ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).EndsendInvoices(result);
            return retVal.Body.sendInvoicesResult;
        }
        
        private System.IAsyncResult OnBeginsendInvoices(object[] inValues, System.AsyncCallback callback, object asyncState) {
            fiscalCalendar.prmExternalsSvc.invoiceType iType = ((fiscalCalendar.prmExternalsSvc.invoiceType)(inValues[0]));
            string jobno = ((string)(inValues[1]));
            decimal amt = ((decimal)(inValues[2]));
            return this.BeginsendInvoices(iType, jobno, amt, callback, asyncState);
        }
        
        private object[] OnEndsendInvoices(System.IAsyncResult result) {
            bool retVal = this.EndsendInvoices(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsendInvoicesCompleted(object state) {
            if ((this.sendInvoicesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.sendInvoicesCompleted(this, new sendInvoicesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void sendInvoicesAsync(fiscalCalendar.prmExternalsSvc.invoiceType iType, string jobno, decimal amt) {
            this.sendInvoicesAsync(iType, jobno, amt, null);
        }
        
        public void sendInvoicesAsync(fiscalCalendar.prmExternalsSvc.invoiceType iType, string jobno, decimal amt, object userState) {
            if ((this.onBeginsendInvoicesDelegate == null)) {
                this.onBeginsendInvoicesDelegate = new BeginOperationDelegate(this.OnBeginsendInvoices);
            }
            if ((this.onEndsendInvoicesDelegate == null)) {
                this.onEndsendInvoicesDelegate = new EndOperationDelegate(this.OnEndsendInvoices);
            }
            if ((this.onsendInvoicesCompletedDelegate == null)) {
                this.onsendInvoicesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsendInvoicesCompleted);
            }
            base.InvokeAsync(this.onBeginsendInvoicesDelegate, new object[] {
                        iType,
                        jobno,
                        amt}, this.onEndsendInvoicesDelegate, this.onsendInvoicesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult fiscalCalendar.prmExternalsSvc.prmExternalsSoap.BeginfiscalPeriods(fiscalCalendar.prmExternalsSvc.fiscalPeriodsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginfiscalPeriods(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginfiscalPeriods(System.AsyncCallback callback, object asyncState) {
            fiscalCalendar.prmExternalsSvc.fiscalPeriodsRequest inValue = new fiscalCalendar.prmExternalsSvc.fiscalPeriodsRequest();
            inValue.Body = new fiscalCalendar.prmExternalsSvc.fiscalPeriodsRequestBody();
            return ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).BeginfiscalPeriods(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fiscalCalendar.prmExternalsSvc.fiscalPeriodsResponse fiscalCalendar.prmExternalsSvc.prmExternalsSoap.EndfiscalPeriods(System.IAsyncResult result) {
            return base.Channel.EndfiscalPeriods(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private fiscalCalendar.prmExternalsSvc.ArrayOfPeriodStructure EndfiscalPeriods(System.IAsyncResult result) {
            fiscalCalendar.prmExternalsSvc.fiscalPeriodsResponse retVal = ((fiscalCalendar.prmExternalsSvc.prmExternalsSoap)(this)).EndfiscalPeriods(result);
            return retVal.Body.fiscalPeriodsResult;
        }
        
        private System.IAsyncResult OnBeginfiscalPeriods(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginfiscalPeriods(callback, asyncState);
        }
        
        private object[] OnEndfiscalPeriods(System.IAsyncResult result) {
            fiscalCalendar.prmExternalsSvc.ArrayOfPeriodStructure retVal = this.EndfiscalPeriods(result);
            return new object[] {
                    retVal};
        }
        
        private void OnfiscalPeriodsCompleted(object state) {
            if ((this.fiscalPeriodsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.fiscalPeriodsCompleted(this, new fiscalPeriodsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void fiscalPeriodsAsync() {
            this.fiscalPeriodsAsync(null);
        }
        
        public void fiscalPeriodsAsync(object userState) {
            if ((this.onBeginfiscalPeriodsDelegate == null)) {
                this.onBeginfiscalPeriodsDelegate = new BeginOperationDelegate(this.OnBeginfiscalPeriods);
            }
            if ((this.onEndfiscalPeriodsDelegate == null)) {
                this.onEndfiscalPeriodsDelegate = new EndOperationDelegate(this.OnEndfiscalPeriods);
            }
            if ((this.onfiscalPeriodsCompletedDelegate == null)) {
                this.onfiscalPeriodsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnfiscalPeriodsCompleted);
            }
            base.InvokeAsync(this.onBeginfiscalPeriodsDelegate, null, this.onEndfiscalPeriodsDelegate, this.onfiscalPeriodsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override fiscalCalendar.prmExternalsSvc.prmExternalsSoap CreateChannel() {
            return new prmExternalsSoapClientChannel(this);
        }
        
        private class prmExternalsSoapClientChannel : ChannelBase<fiscalCalendar.prmExternalsSvc.prmExternalsSoap>, fiscalCalendar.prmExternalsSvc.prmExternalsSoap {
            
            public prmExternalsSoapClientChannel(System.ServiceModel.ClientBase<fiscalCalendar.prmExternalsSvc.prmExternalsSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(fiscalCalendar.prmExternalsSvc.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public fiscalCalendar.prmExternalsSvc.HelloWorldResponse EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                fiscalCalendar.prmExternalsSvc.HelloWorldResponse _result = ((fiscalCalendar.prmExternalsSvc.HelloWorldResponse)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsendResources(fiscalCalendar.prmExternalsSvc.sendResourcesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("sendResources", _args, callback, asyncState);
                return _result;
            }
            
            public fiscalCalendar.prmExternalsSvc.sendResourcesResponse EndsendResources(System.IAsyncResult result) {
                object[] _args = new object[0];
                fiscalCalendar.prmExternalsSvc.sendResourcesResponse _result = ((fiscalCalendar.prmExternalsSvc.sendResourcesResponse)(base.EndInvoke("sendResources", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginlistJobs(fiscalCalendar.prmExternalsSvc.listJobsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("listJobs", _args, callback, asyncState);
                return _result;
            }
            
            public fiscalCalendar.prmExternalsSvc.listJobsResponse EndlistJobs(System.IAsyncResult result) {
                object[] _args = new object[0];
                fiscalCalendar.prmExternalsSvc.listJobsResponse _result = ((fiscalCalendar.prmExternalsSvc.listJobsResponse)(base.EndInvoke("listJobs", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsendInvoices(fiscalCalendar.prmExternalsSvc.sendInvoicesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("sendInvoices", _args, callback, asyncState);
                return _result;
            }
            
            public fiscalCalendar.prmExternalsSvc.sendInvoicesResponse EndsendInvoices(System.IAsyncResult result) {
                object[] _args = new object[0];
                fiscalCalendar.prmExternalsSvc.sendInvoicesResponse _result = ((fiscalCalendar.prmExternalsSvc.sendInvoicesResponse)(base.EndInvoke("sendInvoices", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginfiscalPeriods(fiscalCalendar.prmExternalsSvc.fiscalPeriodsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("fiscalPeriods", _args, callback, asyncState);
                return _result;
            }
            
            public fiscalCalendar.prmExternalsSvc.fiscalPeriodsResponse EndfiscalPeriods(System.IAsyncResult result) {
                object[] _args = new object[0];
                fiscalCalendar.prmExternalsSvc.fiscalPeriodsResponse _result = ((fiscalCalendar.prmExternalsSvc.fiscalPeriodsResponse)(base.EndInvoke("fiscalPeriods", _args, result)));
                return _result;
            }
        }
    }
}
